## Embeddings : 
* Embeddings are the vector representation of text data.That capture semantic meaning and relationship between elements in continuous space.
* LLMs process text by breaking it into tokens and converting them into embeddings.
* Embeddings are the numerical representation of real world data such as text, image, or videos.
* Embeddings are expressed as low-dimensional vectors where the geometrical distance between two vectors in the vector space is a projection of relationships and semantic similarities of two real world objects that the vectors represent.
* Embeddings are the Retrieval and Recommendations.
* Joint Embeddings are when multiple types of objects are being mapped into same Embedding space.


### Types of Embeddings :
* Text Embeddings
* Graph Embeddings
* Word Embeddings
* Training Embeddings
* Document Embeddings
* Image and multimodal Embeddings
* Structured data Embeddings.

## Text Embedding : 


In [24]:
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model2 = AutoModel.from_pretrained("bert-base-uncased")

text = "This is an example for sentence embedding."
inputs2 = tokenizer(text, return_tensors="pt", padding=True, truncation=True)

with torch.no_grad():
    outputs2 = model2(**inputs2)
    text_embedding = outputs2.last_hidden_state.mean(dim=1)
print(text_embedding.shape)
print(text_embedding)

torch.Size([1, 768])
tensor([[-2.6126e-03, -2.7091e-01, -3.7338e-01, -5.1379e-01,  4.1697e-04,
         -1.3386e-01,  3.6756e-01,  4.3727e-01,  3.6357e-02,  1.4245e-01,
         -1.0092e-01, -4.8435e-02, -1.0350e-01, -1.9453e-02, -2.1421e-01,
          2.0226e-01,  3.5399e-02,  2.1110e-02,  2.2002e-01, -3.0476e-01,
          4.2823e-01,  3.8323e-01, -3.4524e-01,  2.4438e-01,  6.7378e-01,
         -3.6252e-01,  9.0263e-02, -2.3172e-01, -5.7007e-01, -5.1940e-02,
          2.4284e-01,  4.1382e-01, -3.8292e-02, -1.6062e-01,  3.4647e-02,
         -3.8272e-01,  4.3262e-01, -2.0029e-01, -1.6066e-01,  1.1960e-01,
         -7.5667e-01, -3.4626e-02,  3.7317e-01,  7.5771e-02,  5.1776e-02,
         -4.8590e-01, -1.7421e-02, -1.8553e-01, -9.3266e-02, -1.8184e-01,
         -1.2089e+00,  3.9868e-01,  3.4692e-01,  2.5726e-01, -3.6809e-01,
          5.2789e-01,  3.7511e-02, -9.7795e-01,  1.9104e-01, -7.3940e-02,
          2.5781e-01,  6.6017e-03, -1.8654e-02, -5.8436e-01,  4.8140e-01,
          3.0733e

## Audio Embeddings

In [31]:
from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2Model
import torch
import librosa

feature_extractor_1 = Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-base-960h")
model1 = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")

audio_file = r"C:\Users\adity\DS_Projects\Langchain\data\audio\ಕಾಂತಾರ 1.wav"
audio, rate = librosa.load(audio_file, sr=16000)
inputs1 = feature_extractor_1(audio, return_tensors="pt", sampling_rate=rate)

with torch.no_grad():
    outputs1 = model1(**inputs1)
    audio_embedding = outputs1.last_hidden_state.mean(dim=1)
print(audio_embedding.shape)
print(audio_embedding)

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\adity\anaconda3\Lib\site-packages\paramiko\pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
C:\Users\adity\anaconda3\Lib\site-packages\paramiko\transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,


torch.Size([1, 768])
tensor([[-6.3591e-03,  2.5209e-02, -1.5583e-02, -3.9151e-02,  8.4238e-02,
         -1.2372e-01,  6.8107e-02, -4.0105e-02,  4.4089e-02, -3.2026e-01,
         -4.2791e-02, -5.9558e-03,  4.1953e-02,  5.9476e-02, -1.4031e-01,
          1.2197e-02, -2.7974e-01,  2.5773e-01,  1.8289e-02,  8.5916e-02,
         -1.8190e-01,  8.3355e-02, -5.7845e-03,  2.6002e-02,  7.6575e-02,
          1.9134e-03, -2.7548e-01,  3.5696e-02, -3.5196e-03, -1.0610e-01,
          1.0139e-01, -1.1119e-02, -5.9351e-02, -4.3585e-02, -1.8250e-01,
         -5.1218e-02,  2.9651e-02, -2.4209e-01, -1.2778e-01,  1.2623e-02,
         -1.1100e-01, -1.7022e-01, -9.2153e-02,  1.9221e-01, -9.4843e-02,
          6.2279e-02, -5.7992e-02, -4.4207e-02, -2.2783e-02,  9.1736e-03,
         -1.1497e-01, -3.9437e-02,  1.0986e-01,  2.5891e-02,  2.6638e-02,
          3.4389e-02,  2.6473e-02, -3.8707e-01, -1.3409e-01, -1.5691e-01,
         -3.1285e-02,  2.7574e-02,  2.1935e-02,  9.0848e-02, -3.0414e-02,
          9.9171e

## Image Embeddings

In [34]:
from transformers import ViTFeatureExtractor, ViTModel
from PIL import Image
import torch

feature_extractor= ViTFeatureExtractor.from_pretrained("google/vit-base-patch16-224-in21k")
model = ViTModel.from_pretrained("google/vit-base-patch16-224-in21k")

image= Image.open(r"C:\Users\adity\DS_Projects\Langchain\data\images\Copy of ARPFIINVOEBTCHLASER (2)_pg1.png").convert("RGB")
inputs = feature_extractor(images=image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)
    image_embedding = outputs.last_hidden_state.mean(dim=1)
print(image_embedding.shape)
print(image_embedding)


C:\Users\adity\anaconda3\Lib\site-packages\transformers\models\vit\feature_extraction_vit.py:30: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(


torch.Size([1, 768])
tensor([[-3.0475e-01, -4.7032e-02, -2.0750e-01, -6.0965e-02,  2.3018e-02,
         -8.8737e-02, -1.2352e-01, -8.0989e-02,  1.0415e-01, -3.8237e-02,
         -1.0796e-01,  1.7425e-01,  1.2619e-01,  5.6769e-02, -1.6511e-03,
          1.4652e-01,  2.1816e-01, -1.1660e-01,  2.2135e-01, -5.0389e-03,
         -4.9071e-02,  2.5720e-02, -1.0613e-01,  6.6939e-02,  7.8940e-02,
          4.9617e-02, -3.3822e-02, -3.5286e-01,  4.9382e-03,  8.1782e-02,
          1.0831e-01, -2.0897e-01,  1.5630e-01, -1.7230e-01, -1.3412e-01,
          1.6881e-01, -2.0457e-01, -2.6371e-01, -2.5897e-01, -2.5942e-01,
         -4.4151e-02, -9.5926e-02,  4.1953e-02, -1.1554e-01,  2.3995e-02,
          3.0582e-01,  1.1000e-01,  1.6859e-01, -2.3990e-03,  7.6852e-02,
          1.5311e-01,  1.4221e-01,  1.0585e-01, -3.6626e-01,  3.8158e-02,
         -2.1289e-01, -3.2849e-02, -3.2440e-02, -1.0838e-01,  1.2008e-01,
         -2.8184e-03,  2.4652e-02, -4.9902e-02,  1.2221e-01,  5.2280e-02,
         -5.3172e

In [36]:
# Combining Embeddings


combined_embedding = torch.cat([image_embedding, audio_embedding, text_embedding])
print("Combined_embedding shape : ", combined_embedding.shape)

Combined_embedding shape :  torch.Size([3, 768])


## Storing Embeddings in Vector Databases-- ChromaDB

In [48]:
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.documents import Document

embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

chroma_db = Chroma(persist_directory="./chroma_db",
                   embedding_function=embedding_model)


documents = [
    Document(page_content="Elon Musk Leads Tesla and SpaceX", metadata={"source": "1"}),
    Document(page_content="Tesla's mission is to accelerate the world's transition to sustainable energy.", metadata={"source": "2"}),
    Document(page_content="SpaceX aims to make space travel more affordable and accessible.", metadata={"source": "3"}),
]

chroma_db.add_documents(documents)

['1f02876a-478d-4bfc-919d-bc91368f57c6',
 'e1c36434-45fd-4c36-9ab2-6e292a9280e5',
 '225e4551-c7b2-4560-8943-eb17a031c0fb']

In [50]:
query_text = "What is Tesla's mission?"
results = chroma_db.similarity_search(query_text, k=2)

for idx, result in enumerate(results, 1):
    print(f"result{idx}: {result.page_content}")
    print(f"Content : {result.page_content}")
    print(f"Metadata : {result.metadata}")

result1: Tesla's mission is to accelerate the world's transition to sustainable energy.
Content : Tesla's mission is to accelerate the world's transition to sustainable energy.
Metadata : {'source': '2'}
result2: Elon Musk Leads Tesla and SpaceX
Content : Elon Musk Leads Tesla and SpaceX
Metadata : {'source': '1'}


## FAISS

In [57]:
!pip install faiss-cpu

   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   --- ------------------------------------ 1.8/18.9 MB 11.2 MB/s eta 0:00:02
   -------- ------------------------------- 3.9/18.9 MB 11.7 MB/s eta 0:00:02
   ------------- -------------------------- 6.6/18.9 MB 10.9 MB/s eta 0:00:02
   ------------------ --------------------- 8.9/18.9 MB 11.3 MB/s eta 0:00:01
   --------------------- ------------------ 10.2/18.9 MB 11.0 MB/s eta 0:00:01
   ------------------------ --------------- 11.8/18.9 MB 10.1 MB/s eta 0:00:01
   ------------------------------- -------- 14.9/18.9 MB 10.4 MB/s eta 0:00:01
   ---------------------------------- ----- 16.5/18.9 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------  18.6/18.9 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------- 18.9/18.9 MB 9.4 MB/s eta 0:00:00


In [59]:
import faiss 
import numpy as np
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

documents = [
    {"id": "1", "text": "Elon Musk owner of Spacex and tesla."},
    {"id": "2", "text": "Tesla's mission is to accelerate the worlds transition to sustainable energy."},
    {"id": "3", "text": "SpaceX aims to make space travel more affordable and accessible"},
]

doc_texts = [doc["text"] for doc in documents]
doc_ids = [doc["id"] for doc in documents]
embeddings = embedding_model.encode(doc_texts)

In [65]:
embedding_dim = embeddings.shape[1]
index = faiss.IndexFlatL2(embedding_dim)

index.add(embeddings)

query_text = "What is Tesla's mission?"
query_embedding = embedding_model.encode([query_text])

k=2
distances, indices = index.search(query_embedding, k)

print("Query:", query_text)
for i, idx in enumerate(indices[0]):
    print(f"\nResult {i+1}:")
    print(f"Text: {doc_texts[idx]}")
    print(f"Distance: {distances[0][i]:.4f}")

Query: What is Tesla's mission?

Result 1:
Text: Tesla's mission is to accelerate the worlds transition to sustainable energy.
Distance: 0.5428

Result 2:
Text: Elon Musk owner of Spacex and tesla.
Distance: 1.0169
